### ISSUE TITLE
Improve imaging plots

### ISSUE THREAD

**Issue by tsalo** [NBCLab/nimare-paper#1]
The brain map figures that are being generated are not the most attractive. I'd like to improve them, but I'm not the most familiar with nilearn's plotting functions.

There are two elements I'd particularly like to fix:

- [x] Axis titles overlap with the brains
- [x] Bi-directional plots (e.g., ALESubtraction) have black around zero in the default color map. We should either threshold the plots, which I don't love, or find a color map that looks better.

**Comment by tsalo** [comment]
Tagging @62442katieb

**Comment by 62442katieb** [comment]
Hi! I looked over the plots last week. I agree with changing colormaps, that was something I noticed while looking them over. I'll try some things out and get back to you with recommendations.

**Comment by 62442katieb** [comment]
I took a look. You could switch up colormaps to something like `RdBu` or `RdYlBu` from `matplotlib`, which have white/yellow around zero:
![diverging](https://user-images.githubusercontent.com/14095475/111339071-d7705880-864d-11eb-831b-e2e6d7c591c3.png)

And then use `Reds` and/or `YlOrRd` for any plots that are all val > 0, for consistency across plots (if that's important to you):
![sequential](https://user-images.githubusercontent.com/14095475/111339306-0ab2e780-864e-11eb-950b-3a775f18b4de.png)

and then change the `alpha` value, so that the anatomy shows through a bit.

**Comment by 62442katieb** [comment]
As for the labels' overlap, you could plot the images on a figure + axis (see [here](https://github.com/nilearn/nilearn/issues/450)), then instead of using nilearn's title param, add a title to the axis itself.

**Comment by tsalo** [comment]
Thanks! I'll try out `RdBu_R` for the bidirectional ones and `Reds` for the unidirectional ones. I'll also try out the separate title approach.

**Comment by tsalo** [comment]
I think I've got it working fairly nicely. @62442katieb would you mind taking a look at the current figures (svg files in the `figures/` subfolder) to see if there's anything else you'd recommend?

**Comment by 62442katieb** [comment]
They look way better! My only note is on the plots that include zero values (e.g., MKDAChi2 on Fig4 and ALE on Fig7) you could threshold at a very close to zero number and avoid a sea of whitish:
>`threshold` : a number, None, or ‘auto’, optional
If None is given, the image is not thresholded. If a number is given, it is used to threshold the image: values below the threshold (in absolute value) are plotted as transparent.

But if the zero values are an aspect you're trying to highlight, disregard that suggestion.
